# Generated by Django 5.2.8 on 2025-11-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_category_delete_post_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='article'),
        ),
    ]
