# Generated by Django 5.2.8 on 2025-12-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated', '-date')},
        ),
    ]
