# Generated by Django 5.2.8 on 2025-12-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
